export const ADD_TODO = "ADD_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const FILTER_TODOS = "FILTER_TODOS";

export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const FETCHING_TODOS = "FETCHING_TODOS";
export const FETCHING_TODOS_SUCCESS = "FETCHING_TODOS_SUCCESS";
export const FETCHING_TODOS_FAILURE = "FETCHING_TODOS_FAILURE";